apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketing-dev-297811
  artifacts:
    - image: aidenhsy/frontend
      # - image: asia.gcr.io/ticketing-dev-297811/frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: aidenhsy/backend
      # - image: asia.gcr.io/ticketing-dev-297811/backend
      context: backend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.ts"
            dest: .
